In [1]:
import torch

In [2]:
#Case 1, affine = False. In this case, this layer hebaviors statelessly.
layer = torch.nn.BatchNorm1d(2, momentum=0.1, affine=False, track_running_stats=False).train()
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[2, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [2, 0], [3, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print()
layer.eval()
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[2, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [2, 0], [3, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print(F"weight: {layer.weight}")
print(F"bias:   {layer.bias}")

tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]])
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]])
tensor([[-1.2247,  0.0000],
        [ 0.0000,  0.0000],
        [ 1.2247,  0.0000]])
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]])

tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]])
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]])
tensor([[-1.2247,  0.0000],
        [ 0.0000,  0.0000],
        [ 1.2247,  0.0000]])
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]])
weight: None
bias:   None


In [3]:
#Case 1, affine = True. In this case, this layer still hebaviors statelessly.
layer = torch.nn.BatchNorm1d(2, momentum=0.1, track_running_stats=False).train()#affine = True as default
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[2, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [2, 0], [3, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print()
layer.eval()
#print(layer.training)#False
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[2, 0], [0, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [2, 0], [3, 0]], dtype = torch.float32)))
print(layer(torch.tensor([[1, 0], [0, 0]], dtype = torch.float32)))
print(F"weight: {layer.weight}")
print(F"bias:   {layer.bias}")

tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]], grad_fn=<NativeBatchNormBackward0>)
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]], grad_fn=<NativeBatchNormBackward0>)
tensor([[-1.2247,  0.0000],
        [ 0.0000,  0.0000],
        [ 1.2247,  0.0000]], grad_fn=<NativeBatchNormBackward0>)
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]], grad_fn=<NativeBatchNormBackward0>)

tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]], grad_fn=<NativeBatchNormBackward0>)
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]], grad_fn=<NativeBatchNormBackward0>)
tensor([[-1.2247,  0.0000],
        [ 0.0000,  0.0000],
        [ 1.2247,  0.0000]], grad_fn=<NativeBatchNormBackward0>)
tensor([[ 1.0000,  0.0000],
        [-1.0000,  0.0000]], grad_fn=<NativeBatchNormBackward0>)
weight: Parameter containing:
tensor([1., 1.], requires_grad=True)
bias:   Parameter containing:
tensor([0., 0.], requires_grad=True)
