In [1]:
import torch

In [2]:
layer = torch.nn.Conv1d(in_channels = 4, out_channels = 5, kernel_size = 6, bias = False)
print(F"===weight shape===  {layer.weight.shape}")
input = torch.rand(7,4,8)
print(F"===output shape===  {layer(input).shape}")

===weight shape===  torch.Size([5, 4, 6])
===output shape===  torch.Size([7, 5, 3])


In [3]:
#test 1, basic without bias.
input = torch.tensor([1, 2, 4, 8], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.11], dtype = torch.float32, requires_grad = True).view(layer.weight.shape))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 4., 8.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1100]]], requires_grad=True)
===result===  tensor([[[1.2200, 2.4400, 4.8800]]], grad_fn=<ConvolutionBackward0>)


In [4]:
#test 2, bias.
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1, 1], dtype = torch.float32, requires_grad = True).view(layer.weight.shape))
print(F"===weight===  {layer.weight}")
print(F"===bias shape===  {layer.bias.shape}")
layer.bias = torch.nn.parameter.Parameter(torch.tensor([100], dtype = torch.float32, requires_grad = True))
print(F"===bias===  {layer.bias}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1., 1.]]], requires_grad=True)
===bias shape===  torch.Size([1])
===bias===  Parameter containing:
tensor([100.], requires_grad=True)
===result===  tensor([[[103., 105.]]], grad_fn=<ConvolutionBackward0>)


In [5]:
#test 3, stride
input = torch.tensor([1, 2, 3, 4, 5], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, stride = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.11], dtype = torch.float32, requires_grad = True).view(layer.weight.shape))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3., 4., 5.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1100]]], requires_grad=True)
===result===  tensor([[[1.2200, 3.4400]]], grad_fn=<ConvolutionBackward0>)


In [6]:
#test 4, padding, case 1, padding = 1
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, padding = 1)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.1], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1000]]], requires_grad=True)
===result===  tensor([[[0.1000, 1.2000, 2.3000, 3.0000]]], grad_fn=<ConvolutionBackward0>)


In [7]:
#test 4, padding, case 2, padding = 2
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, padding = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.1], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1000]]], requires_grad=True)
===result===  tensor([[[0.0000, 0.1000, 1.2000, 2.3000, 3.0000, 0.0000]]],
       grad_fn=<ConvolutionBackward0>)


In [8]:
#test 5, groups. I don't know how this would help in any means. But it's there. 
input = torch.tensor([1, 2, 4, 8, 100, 200, 400, 800], dtype = torch.float32).view(1, 4, 2)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 4, out_channels = 2, kernel_size = 2, bias = False, groups = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1000, 100, 10, 1., 1, 1.01, 1.0101, 1.010101], dtype = torch.float32, requires_grad = True).view(*layer.weight.shape))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[  1.,   2.],
         [  4.,   8.],
         [100., 200.],
         [400., 800.]]])
===weight shape===  torch.Size([2, 2, 2])
===weight===  Parameter containing:
tensor([[[1000.0000,  100.0000],
         [  10.0000,    1.0000]],

        [[   1.0000,    1.0100],
         [   1.0101,    1.0101]]], requires_grad=True)
===result===  tensor([[[1248.0000],
         [1514.1207]]], grad_fn=<ConvolutionBackward0>)


In [9]:
#test 6, dilation.
input = torch.tensor([1, 2, 3, 4, 5], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, dilation = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.1], dtype = torch.float32, requires_grad = True).view(*layer.weight.shape))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3., 4., 5.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1000]]], requires_grad=True)
===result===  tensor([[[1.3000, 2.4000, 3.5000]]], grad_fn=<ConvolutionBackward0>)


In [10]:
#test 7, padding mode, case 1, zeros. No limitation for the padding value.
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 1, bias = False, padding = 7, padding_mode = "zeros")
#print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1.], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
#print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===result===  tensor([[[0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0.]]],
       grad_fn=<ConvolutionBackward0>)


In [11]:
#test 7, padding mode, case 2, replicate. No limitation for the padding value.
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 1, bias = False, padding = 7, padding_mode = "replicate")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1.], dtype = torch.float32, requires_grad = True).view(1, 1, -1))

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===result===  tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 2., 3., 3., 3., 3., 3., 3., 3., 3.]]],
       grad_fn=<ConvolutionBackward0>)


In [12]:
#test 7, padding mode, case 3, reflect. Notice, the max padding value is the size of input - 1. 
#In this case, size of input is 4, the max padding value is 3.
input = torch.tensor([1, 2, 3, 4], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 1, bias = False, padding = 3, padding_mode = "reflect")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1.], dtype = torch.float32, requires_grad = True).view(1, 1, -1))

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3., 4.]]])
===result===  tensor([[[4., 3., 2., 1., 2., 3., 4., 3., 2., 1.]]],
       grad_fn=<ConvolutionBackward0>)


In [13]:
#test 7, padding mode, case 4, circular. Notice, the max padding value is the same as size of input.
#In this case, size of input is 3, the max padding value is also 3.
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.Conv1d(in_channels = 1, out_channels = 1, kernel_size = 1, bias = False, padding = 3, padding_mode = "circular")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1.], dtype = torch.float32, requires_grad = True).view(1, 1, -1))

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===result===  tensor([[[1., 2., 3., 1., 2., 3., 1., 2., 3.]]],
       grad_fn=<ConvolutionBackward0>)
