In [1]:
import torch

In [2]:
layer = torch.nn.ConvTranspose1d(in_channels = 3, out_channels = 4, kernel_size = 5, bias = False)
print(F"===weight shape===  {layer.weight.shape}")
input = torch.rand(6, 3, 7)
print(F"===output shape===  {layer(input).shape}")

===weight shape===  torch.Size([3, 4, 5])
===output shape===  torch.Size([6, 4, 11])


In [3]:
#test 1, basic without bias.
input = torch.tensor([1, 2, 4], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.ConvTranspose1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.11], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 4.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1100]]], requires_grad=True)
===result===  tensor([[[1.0000, 2.1100, 4.2200, 0.4400]]], grad_fn=<ConvolutionBackward0>)


In [4]:
#test 2, bias.
input = torch.tensor([1, 1], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.ConvTranspose1d(in_channels = 1, out_channels = 1, kernel_size = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1, 1], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {layer.weight}")
print(F"===bias shape===  {layer.bias.shape}")
layer.bias = torch.nn.parameter.Parameter(torch.tensor([100], dtype = torch.float32, requires_grad = True))
print(F"===bias===  {layer.bias}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 1.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1., 1.]]], requires_grad=True)
===bias shape===  torch.Size([1])
===bias===  Parameter containing:
tensor([100.], requires_grad=True)
===result===  tensor([[[101., 102., 101.]]], grad_fn=<ConvolutionBackward0>)


In [5]:
#test 3, stride
input = torch.tensor([1, 2], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.ConvTranspose1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, stride = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.11], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1100]]], requires_grad=True)
===result===  tensor([[[1.0000, 0.1100, 2.0000, 0.2200]]], grad_fn=<ConvolutionBackward0>)


In [6]:
#test 4, padding
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.ConvTranspose1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, padding = 1)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.11], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===weight shape===  torch.Size([1, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000, 0.1100]]], requires_grad=True)
===result===  tensor([[[2.1100, 3.2200]]], grad_fn=<ConvolutionBackward0>)


In [7]:
#test 5, groups. I don't know how this would help in any means. But it's there. 
input = torch.tensor([1, 2, 3, 4], dtype = torch.float32).view(1, 4, 1)
print(F"===input===  {input}")

layer = torch.nn.ConvTranspose1d(in_channels = 4, out_channels = 2, kernel_size = 2, bias = False, groups = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.1, 0.01, 0.001, 1e-4, 1e-5, 1e-6, 1e-7], dtype = torch.float32, requires_grad = True).view(*layer.weight.shape))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1.],
         [2.],
         [3.],
         [4.]]])
===weight shape===  torch.Size([4, 1, 2])
===weight===  Parameter containing:
tensor([[[1.0000e+00, 1.0000e-01]],

        [[1.0000e-02, 1.0000e-03]],

        [[1.0000e-04, 1.0000e-05]],

        [[1.0000e-06, 1.0000e-07]]], requires_grad=True)
===result===  tensor([[[1.0200e+00, 1.0200e-01],
         [3.0400e-04, 3.0400e-05]]], grad_fn=<ConvolutionBackward0>)


In [8]:
#test 6, dilation.
input = torch.tensor([1, 2, 3], dtype = torch.float32).view(1, 1, 3)
print(F"===input===  {input}")

layer = torch.nn.ConvTranspose1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, dilation = 2)
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.1], dtype = torch.float32, requires_grad = True).view(*l.weight.shape))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

===input===  tensor([[[1., 2., 3.]]])
===weight shape===  torch.Size([1, 1, 2])


NameError: name 'l' is not defined

In [ ]:
#test , output_padding case 1, output_padding < stride
input = torch.tensor([1, 2], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

layer = torch.nn.ConvTranspose1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, output_padding = 1, stride = 2 )
print(F"===weight shape===  {layer.weight.shape}")
layer.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.1], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {layer.weight}")

print(F"===result===  {layer(input)}")

In [ ]:
#test , output_padding case 1, output_padding < stride
input = torch.tensor([1, 2], dtype = torch.float32).view(1, 1, -1)
print(F"===input===  {input}")

l = torch.nn.ConvTranspose1d(in_channels = 1, out_channels = 1, kernel_size = 2, bias = False, output_padding = 1, dilation = 2 )
print(F"===weight shape===  {l.weight.shape}")
l.weight = torch.nn.parameter.Parameter(torch.tensor([1., 0.1], dtype = torch.float32, requires_grad = True).view(1, 1, -1))
print(F"===weight===  {l.weight}")

print(F"===result===  {l(input)}")